### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by mahdialibi** [JaesikKim/HiG2Vec#6]
Hi, can you provide an exact requirement file with versions?
it seems that we can't make it working with new versions of libraries
this is my requirement file
```
Cython==0.29.33
future==0.18.3
joblib==1.2.0
numpy==1.24.2
pandas==1.5.3
Pillow==9.4.0
python-dateutil==2.8.2
pytz==2022.7.1
scikit-learn==1.2.2
scipy==1.10.1
six==1.16.0
threadpoolctl==3.1.0
torch==1.6.0+cpu
torchvision==0.7.0+cpu
tqdm==4.65.0
```
when running python setup.py build_ext --inplace 
I get an error
`Compiling hype/graph_dataset.pyx because it changed.
[1/1] Cythonizing hype/graph_dataset.pyx
/home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/malibi/HiG2Vec/hype/graph_dataset.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'hype.graph_dataset' extension
creating build
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/hype
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/numpy/core/include -I/home/malibi/HiG2Vec/.venv/include -I/usr/local/include/python3.8 -c hype/graph_dataset.cpp -o build/temp.linux-x86_64-3.8/hype/graph_dataset.o -std=c++11
In file included from /home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940:0,
                 from /home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from hype/graph_dataset.cpp:786:
/home/malibi/HiG2Vec/.venv/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
hype/graph_dataset.cpp: In function ‘long int __pyx_f_4hype_13graph_dataset_14BatchedDataset__getbatch(__pyx_obj_4hype_13graph_dataset_BatchedDataset*, int, __Pyx_memviewslice)’:
hype/graph_dataset.cpp:5612:159: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_2 = ((__pyx_v_negs.size() < ((struct __pyx_vtabstruct_4hype_13graph_dataset_BatchedDataset *)__pyx_v_self->__pyx_vtab)->_nnegatives(__pyx_v_self)) != 0);
                                                                                                                                                               ^
g++ -pthread -shared build/temp.linux-x86_64-3.8/hype/graph_dataset.o -o /home/malibi/HiG2Vec/hype/graph_dataset.cpython-38-x86_64-linux-gnu.so`

have you any idea how to make it work
thank you

**Comment by JaesikKim** [comment]
Hi @mahdialibi ,
Thanks for your reporting issue.
I just upload my environment.yml , so can you please try to install a new environment with this?

And FYI, the below warning message is from my test.
This is just warning message, so you can ignore it.

`Compiling hype/graph_dataset.pyx because it changed.
[1/1] Cythonizing hype/graph_dataset.pyx
/home/jaesik/anaconda3/envs/hig2vec/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/jaesik/HiG2Vec/HiG2Vec/hype/graph_dataset.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /home/jaesik/anaconda3/envs/hig2vec/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:0,
                 from /home/jaesik/anaconda3/envs/hig2vec/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/jaesik/anaconda3/envs/hig2vec/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from hype/graph_dataset.cpp:786:
/home/jaesik/anaconda3/envs/hig2vec/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
hype/graph_dataset.cpp: In function 'long int __pyx_f_4hype_13graph_dataset_14BatchedDataset__getbatch(__pyx_obj_4hype_13graph_dataset_BatchedDataset*, int, __Pyx_memviewslice)':
hype/graph_dataset.cpp:5612:159: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_2 = ((__pyx_v_negs.size() < ((struct __pyx_vtabstruct_4hype_13graph_dataset_BatchedDataset *)__pyx_v_self->__pyx_vtab)->_nnegatives(__pyx_v_self)) != 0);
        `

**Comment by mahdialibi** [comment]
It seems that my problem is from the numpy version that must be 1.23.5
